/*
 * Copyright (c) by Andreas (oentoro.andreas@gmail.com)
 * created at 5 - 9 - 2020.
 */

/**
 * Created by Andreas on 7/10/2019.
 */

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.9.22'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://oss.jfrog.org/artifactory/oss-snapshot-local/' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    // Sdk and tools
    // Support library and architecture components support minSdk 14 and above.
    // App dependencies
    materialDesignVersion = '1.11.0'
    cardViewVersion = '1.0.0'
    legacySupportVersion = '1.7.0'
    jUnitVersion = '4.13.2'
    clarifaiVersion = '2.4.0'
    daggerVersion = '2.48'
    retrofitVersion = '2.9.0'
    okhttpVersion = '4.12.0'
    rxjavaVersion = '2.2.21'
    rxAndroidVersion = '2.1.1'
    permissionsDispatcherVersion = '4.9.2'
    glideVersion = '4.16.0'
    firebaseCoreVersion = '21.1.1'
    firebaseAuthVersion = '22.3.0'
    firebaseCloudStoreVersion = '24.10.0'
    firebaseAnalytic = '21.5.0'
    materialDialogVersion = '3.3.0'
    circleIVVersion = '3.1.0'
    roomVersion = '2.6.1'
    zeibatsuVersion = '2.1.1'
    adMobVersion = '22.6.0'
    preferenceVersion = '1.2.1'
    fastAdapterVersion = '5.7.0'

    junitVersion = '4.13.2'
    espressoVersion = '3.5.1'
    mockitoVersion = '5.8.0'
    coreTestingVersion = '2.2.0'
    testRunnerVersion = '1.5.2'
    testExtRunnerVersion = '1.1.5'
    hamcrestVersion = '2.2'
}
